/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const QueueLazyImport = createFileRoute('/queue')()
const PlayLazyImport = createFileRoute('/play')()
const IndexLazyImport = createFileRoute('/')()
const GameGameIdLazyImport = createFileRoute('/game/$gameId')()

// Create/Update Routes

const QueueLazyRoute = QueueLazyImport.update({
  path: '/queue',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/queue.lazy').then((d) => d.Route))

const PlayLazyRoute = PlayLazyImport.update({
  path: '/play',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/play.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const GameGameIdLazyRoute = GameGameIdLazyImport.update({
  path: '/game/$gameId',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/game/$gameId.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/play': {
      preLoaderRoute: typeof PlayLazyImport
      parentRoute: typeof rootRoute
    }
    '/queue': {
      preLoaderRoute: typeof QueueLazyImport
      parentRoute: typeof rootRoute
    }
    '/game/$gameId': {
      preLoaderRoute: typeof GameGameIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  PlayLazyRoute,
  QueueLazyRoute,
  GameGameIdLazyRoute,
])

/* prettier-ignore-end */
